
name: Trigger on release

on:
  release
#    types: created, edited #change to published when ready for production

jobs:
  Test_Github_API:
    runs-on: ubuntu-latest
    name: Test Github API values
    
    steps:
      - name: View context attributes
        uses: actions/github-script@v3
        with:
          script: console.log(context)
