name: Create release

on:
   push:
    # branches to consider in the event; optional, defaults to all
    # Although the workflow runs on each push to the following branches, the draft release it creates is based on pull requests to these branches.
    branches:
      - main
      - development
      - release-workflow

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    name: Create/update release based on pull request
    # Outputs make the release info available to the build_and_push_docker_image job
    outputs:
      release_tag: ${{ steps.create_release.outputs.tag_name }}
      release_version: ${{ steps.set-version-variables.outputs.result }}
      release_id: ${{ steps.create_release.outputs.id }}
    steps:
      # Drafts your next Release notes as Pull Requests are merged into above-mentioned branches
      - name: Create release
        id: create_release
        uses: release-drafter/release-drafter@v5
        with: $PREVIOUS_TAG
          tag: 
          config-name: release-drafter.yml # DON'T merge this change into the master branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set version variables
        id: set-version-variables
        uses: actions/github-script@v3        
        with:
          # Grabs the version number from the release tag, minus the "v" on the beginning 
          script: |            
            var str = "${{ steps.create_release.outputs.tag_name }}";
            return str.replace("v", "");
          result-encoding: string